#!/usr/bin/env php
<?php
if (php_sapi_name() !== 'cli') exit;
require __DIR__ . '/../vendor/autoload.php';

$username = readline('Enter username: ');
$password = stripslashes(escapeshellcmd(password_hash(readline('Enter password: '), PASSWORD_BCRYPT)));

(new HeroPress)->dbh->exec("INSERT INTO users (username, password) VALUES ('$username', '$password');");
